#ifndef __AppGUI__
#define __AppGUI__

/**
@file
Subclass of AppGUIBase, which is generated by wxFormBuilder.
*/

#include "AppGUIBase.h"

//// end generated include

/** Implementing AppGUIBase */
class AppGUI : public AppGUIBase {
protected:
    // Handlers for AppGUIBase events.
    void readImgPath(wxCommandEvent &event);

    void readMaskPath(wxCommandEvent &event);

    void changeTransparencyColor(wxColourPickerEvent &event);

    void changeApplyingMethod(wxCommandEvent &event);

    void invertMask(wxCommandEvent &event);

    void applyMask(wxCommandEvent &event);

    void changeAlphaLevel(wxScrollEvent &event);

    void updateCanvas(wxUpdateUIEvent &event);

public:
    /** Constructor */
    AppGUI(wxWindow *parent);
    //// end generated class members

private:
    wxImage image;
    wxImage imageCopy;
    wxImage mask;

};

#endif // __AppGUI__
