#ifndef __AppGUI__
#define __AppGUI__

/**
@file
Subclass of AppGUIBase, which is generated by wxFormBuilder.
*/

#include "AppGUIBase.h"

//// end generated include

/** Implementing AppGUIBase */
class AppGUI : public AppGUIBase {
protected:
    // Handlers for AppGUIBase events.
    void readImgPath(wxCommandEvent &event);
    void readMaskPath(wxCommandEvent &event);
    void changeTransparencyColor(wxColourPickerEvent &event);
    void changeApplyingMethod(wxCommandEvent &event);
    void applyMask(wxCommandEvent &event);
    void saveToFile(wxCommandEvent &event);
    void changeAlphaLevel(wxScrollEvent &event);
    void updateCanvas(wxUpdateUIEvent &event);

public:
    /** Constructor */
    AppGUI(wxWindow *parent);
    //// end generated class members

private:
    wxImage image;
    wxImage imageCopy;
    wxImage mask;
    wxColour transparencyColor;
    enum ApplyingMethod {CHANGE=0, SUM, MULTIPLY, SUBTRACT, LIGHTEN, DARKEN, DIFFERENCE};
    ApplyingMethod method;

    inline wxColor addColors(int& i, int& j);
    inline wxColor changeColors(int& i, int& j);
    inline wxColor multiplyColors(int& i, int& j);
    inline wxColor subtractColors(int &i, int &j);
    inline wxColor differenceBetweenColors(int &i, int &j);
    inline wxColor onlyLighten(int &i, int &j);
    inline wxColor onlyDarken(int &i, int &j);

    inline void correctColor(int &computedColor);
    inline bool isColorTransparent(int &i, int &j);
};

#endif // __AppGUI__
