#ifndef __AppGUI__
#define __AppGUI__

/**
@file
Subclass of AppGUIBase, which is generated by wxFormBuilder.
*/

#include "AppGUIBase.h"

//// end generated include

/** Implementing AppGUIBase */
class AppGUI : public AppGUIBase {
protected:
    // Handlers for AppGUIBase events.
    void readImgPath(wxCommandEvent &event);
    void readMaskPath(wxCommandEvent &event);
    void changeTransparencyColor(wxColourPickerEvent &event);
    void changeApplyingMethod(wxCommandEvent &event);
    void applyMask(wxCommandEvent &event);
    void changeAlphaLevel(wxScrollEvent &event);
    void updateCanvas(wxUpdateUIEvent &event);

public:
    /** Constructor */
    AppGUI(wxWindow *parent);
    //// end generated class members

private:
    wxImage image;
    wxImage imageCopy;
    wxImage mask;
    wxColour transparencyColor;
    enum ApplyingMethod {CHANGE_COLORS=0, SUM_COLORS, MULTIPLY_COLORS};
    ApplyingMethod method;

    wxColour addColors(int i, int j);
    wxColor changeColors(int i, int j);
    wxColor multiplyColors(int i, int j);

    void correctColor(int &red);
    bool colorTransparent(int i, int j);

};

#endif // __AppGUI__
